### ISSUE TITLE
[NEXT 9th Assignment] Session 0 - Git과 Github 개론

### ISSUE THREAD

**Issue by OrcaLion** [NEXT-LIKELION/NEXTx9th#1]
자신 만의 과제 레포지토리 만든 다음에 Session0_HW 디렉토리 밑에 본인 만의 README작성해보기 (~3.22)

1. 이름 
2. 과제 링크

**Comment by Parkhanyoung** [comment]
1. 박한영
2. https://github.com/Parkhanyoung/FirstRepository

**Comment by rkdud007** [comment]
1. 박가영
2. https://github.com/rkdud007/Session0_HW

**Comment by Parkhanyoung** [comment]
1. 박한영
2. https://github.com/Parkhanyoung/Repository-for-HW/tree/master/Session0_HW

**Comment by developpeurenmoi** [comment]
1. 진서동
2. https://github.com/developpeurenmoi/Homework/tree/master/Session0_HW

**Comment by kyliecamila** [comment]
1. 강미지
2. https://github.com/kyliecamila/Assignment

**Comment by hooNode** [comment]
1. 김태훈
2. https://github.com/kth7024/Session0_HW

**Comment by INJAESEO** [comment]
1. 서인재
2. https://github.com/INJAESEO/seoinjae/tree/master/Session0_HW

**Comment by gyeonglin** [comment]
1. 김경린
2. https://github.com/kyoungLin/NEXT_HW/tree/master/Session0_HW

**Comment by KongDagam** [comment]
1. 공다감
2. https://github.com/KongDagam/HW/blob/master/README.md

**Comment by yilin-kim** [comment]
1. 김이린
2. https://github.com/yilin-kim/Session0_HW

**Comment by Minyongggg** [comment]
1. 이민용
2. https://github.com/Minyongggg/Next_assign/tree/master/Session0_HW

**Comment by dlwnsdud1104** [comment]
1. 이준영
2. https://github.com/dlwnsdud1104/HWRepository

**Comment by chaliechu117** [comment]
1. 추창욱
2. https://github.com/chaliechu117/Session0_HW

**Comment by gadongkim** [comment]
1. 김가현
2. https://github.com/gadongkim/NEXT_HW

**Comment by toto9602** [comment]
1. 김동민
2. https://github.com/toto9602/Repository_HW/tree/master/Session0_HW

**Comment by High-Shine** [comment]
1. 최재혁
2. https://github.com/High-Shine/NEXTx9th/tree/master/Session0_HW

**Comment by deborah91298** [comment]
1. 전혜린
2. https://github.com/deborah91298/NEXTLikeLion/blob/master/Session0_HW/README.md

**Comment by jiyoon27** [comment]
1. 정지윤
2. https://github.com/jiyoon27/NEXT_HW/tree/master/Session_0

**Comment by minqrii** [comment]
1. 김민규
2. https://github.com/minqrii/Repository-NEXT_HW

**Comment by existentialist2001** [comment]
1. 주송준
2. https://github.com/existentialist2001/NEXT_HW/blob/master/Session0/README.md

**Comment by 45-5DC** [comment]
1. 이상헌
2. https://github.com/45-5DC/NEXT_HW/blob/master/Session0_HW/README.md

**Comment by Jamiejaja** [comment]
1. 이재아
2. https://github.com/Jamiejaja/NEXT_HW.git

**Comment by suyeoni4731** [comment]
1. 성수연
2. https://github.com/suyeoni4731/Session0

**Comment by zznbbang** [comment]
1. 양진영
2. https://github.com/zznbbang/REPOSITORY_HW.git

**Comment by gjivaeri** [comment]
1. 박설진
2. https://github.com/gjivaeri/NEXT_HW/tree/master/Session0_HW

**Comment by yunzzo** [comment]
1. 배윤주
2. https://github.com/yunzzo/LIKE_LION_HW/tree/main/Session0_HW

**Comment by yunzzo** [comment]
1. 배윤주
2. https://github.com/yunzzo/LIKE_LION_HW/tree/main/Session0_HW

**Comment by KongDagam** [comment]
1. 공다감
2. https://github.com/KongDagam/NEXT_HW/tree/master/Session0_HW

**Comment by suyeoni4731** [comment]
1. 성수연
2. https://github.com/suyeoni4731/Session0

**Comment by chaliechu117** [comment]
1. 추창욱
2. https://github.com/chaliechu117/NEXT_HW

**Comment by onCloud33** [comment]
1. 양효령
2. https://github.com/HyoRyoung-Yang/NEXT_HW

**Comment by kyulee0103** [comment]
1. 권규리
2. https://github.com/kyulee0103/NEXT_HW/tree/master/session0

**Comment by shinwr** [comment]
1. 신원령
2. https://github.com/shinwr/Homework.git

**Comment by pcw9341** [comment]
1. 박채원
2. https://github.com/pcw9341/Repository_HW

**Comment by Kim-Jiseong** [comment]
1. 김지성
2. https://github.com/Kim-Jiseong/NEXT_HW.git

**Comment by heawon99** [comment]
1. 양희원
2. https://github.com/heawon99/Repository-NEXT_HW.git
