### ISSUE TITLE
[NEXT 9th Assignment] Session 1 - HTML/CSS

### ISSUE THREAD

**Issue by jeehyunlyu** [NEXT-LIKELION/NEXTx9th#2]
1. 다음의 3가지 강의를 수강해주세요.

<HTML/CSS>  (마감: 3/25 세션 전)
  - Learn HTML 
  - Learn CSS 

<Python>  (마감: 3/29 세션 전)
  - Python3 (Pro) 

📌 Syllabus 탭에서 ‘Interactive lesson’이 표기된 강의만 수강해주세요. (퀴즈, 프로젝트 부분 제외)

📌 코드카데미 수강 완료 인증화면을 캡쳐해서 3/25, 3/29 세션까지 마감인 과제들과 함께 세션 폴더에 넣어서 깃헙에 업로드해주세요:)

2. HTML/CSS로 나만의 블로그 꾸미기

📌 강의안에 적혀있는 조건들을 모두 포함해서 제작해주시면 됩니다:) 어제 배운 내용들을 최대한 많이 연습해보시고, 배우지 않은 내용들도 필요하다고 생각하시면 넣으셔도 됩니다ㅎㅎ

📌 댓글로 과제 인증해주실 때 다음 내용들 포함해주세요!

1) 이름
2) 깃헙 링크
     : Session1 폴더 안에 블로그 html/css 파일, 코드카데미 수강 완료 인증 화면
3) 제작한 블로그 화면 캡쳐
     : 화면 비율 100%를 조정해서 캡쳐해주셔도 되고, 부분을 나누어 캡쳐해주셔도 됩니다:)

**Comment by existentialist2001** [comment]
1. 주송준
2. https://github.com/existentialist2001/NEXT_HW/tree/master/Session1%20%EA%B3%BC%EC%A0%9C
3. 
![blog capture](https://user-images.githubusercontent.com/77263832/112353239-e8d0f900-8d0e-11eb-8ea1-e23c22a81203.png)

**Comment by KongDagam** [comment]
1. 공다감
2. https://github.com/KongDagam/NEXT_HW/tree/master/Session1_HW
3. 
<img width="960" alt="KakaoTalk_20210325_002024954" src="https://user-images.githubusercontent.com/80804600/112354552-25512480-8d10-11eb-9399-60f92ebc7651.png">
<img width="960" alt="KakaoTalk_20210325_002052669" src="https://user-images.githubusercontent.com/80804600/112354561-271ae800-8d10-11eb-88a9-8bdab69a9520.png">

**Comment by chaliechu117** [comment]
1. 추창욱
2. https://github.com/chaliechu117/NEXT_HW/tree/master/Session_1
3. 
![블로그화면캡처(추창욱)](https://user-images.githubusercontent.com/80829113/112366311-ffca1800-8d1b-11eb-860d-e3fe3418e5ad.png)

**Comment by rkdud007** [comment]
1. 박가영
2. https://github.com/rkdud007/NEXT-X-likelion/tree/master/Session1_HW
3. 
![블로그1](https://user-images.githubusercontent.com/76558220/112414269-2496ad80-8d65-11eb-9d95-982c25e50eef.PNG)
![캡처3](https://user-images.githubusercontent.com/76558220/112414279-282a3480-8d65-11eb-9e7f-ee6f81267916.PNG)
![캡처2](https://user-images.githubusercontent.com/76558220/112414306-2eb8ac00-8d65-11eb-97dd-07cf35f2c5d4.PNG)
![캡처5](https://user-images.githubusercontent.com/76558220/112414331-35dfba00-8d65-11eb-87f0-2d337d120eb4.PNG)
![캡처4](https://user-images.githubusercontent.com/76558220/112414352-3d9f5e80-8d65-11eb-8f04-14686cd5d31e.PNG)

**Comment by toto9602** [comment]
1. 김동민
2. https://github.com/toto9602/Repository_HW/tree/master/Session1_HW
3. 
![블로그 캡처1](https://user-images.githubusercontent.com/80831518/112416536-35492280-8d69-11eb-8317-82207ef5be3c.PNG)
![블로그 캡처2](https://user-images.githubusercontent.com/80831518/112416541-39754000-8d69-11eb-8fe9-292d7a6f44d4.PNG)
![블로그 캡처3](https://user-images.githubusercontent.com/80831518/112416548-3bd79a00-8d69-11eb-9348-f320044938b7.PNG)

**Comment by hooNode** [comment]
1. 김태훈
2.  https://github.com/kth7024/Session1_HW
3. 
![image](https://user-images.githubusercontent.com/56389950/112418905-bbfffe80-8d6d-11eb-9f47-e5699bd118f9.png)

**Comment by High-Shine** [comment]
1. 최재혁
2. https://github.com/High-Shine/NEXTx9th/tree/master/Session1_HW
3. 
![Blog certi](https://user-images.githubusercontent.com/80829504/112423660-6c720080-8d76-11eb-8fb1-b1f3a3c4108f.jpg)

**Comment by yunzzo** [comment]
1. 배윤주
2. https://github.com/yunzzo/LIKE_LION_HW/tree/master/Session1
3.
![html_capture](https://user-images.githubusercontent.com/77669704/112433469-a4cd0b00-8d85-11eb-92bb-a470fff9b386.png)

**Comment by suyeoni4731** [comment]
1. 성수연
2. https://github.com/suyeoni4731/NEXT_HW
3. 
![블로그](https://user-images.githubusercontent.com/80872646/112440880-2c1e7c80-8d8e-11eb-9027-3b28d65ed9ef.png)
![블로그2](https://user-images.githubusercontent.com/80872646/112441154-76076280-8d8e-11eb-855f-cc9ea9c1d88b.png)

**Comment by INJAESEO** [comment]
1. 서인재
2. https://github.com/INJAESEO/NEXT_HW/tree/master/Session1_HW
3. 
![블로그_1](https://user-images.githubusercontent.com/80825535/112444358-4b6ad900-8d91-11eb-8dec-351365d6da9a.png)
![블로그_2](https://user-images.githubusercontent.com/80825535/112444368-4e65c980-8d91-11eb-80a3-f3bce8941835.png)

**Comment by minqrii** [comment]
1. 김민규
2. https://github.com/minqrii/Repository-NEXT_HW/tree/master/Session1-1
3. 
![1](https://user-images.githubusercontent.com/80770871/112445637-b537b280-8d92-11eb-829d-313beacc20be.png)
![2](https://user-images.githubusercontent.com/80770871/112445640-b668df80-8d92-11eb-8d74-3bac2db9644a.png)
![3](https://user-images.githubusercontent.com/80770871/112445642-b7017600-8d92-11eb-991a-59d93fdf2e4a.png)
![4](https://user-images.githubusercontent.com/80770871/112445643-b7017600-8d92-11eb-9d58-2a235c0c984e.png)

**Comment by Parkhanyoung** [comment]
1. 박한영
2. https://github.com/Parkhanyoung/Repository-for-HW/tree/master/Session1-HW
3. 
![블로그 이미지](https://user-images.githubusercontent.com/80797824/112446287-64748980-8d93-11eb-81f6-48c453040dcf.png)
![블로그2](https://user-images.githubusercontent.com/80797824/112446304-676f7a00-8d93-11eb-827b-de6f4ef7543d.png)

**Comment by kyulee0103** [comment]
1. 권규리
2. https://github.com/kyulee0103/NEXT_HW/tree/master/Session1_HW
3. 
![image](https://user-images.githubusercontent.com/80827003/112447405-a18d4b80-8d94-11eb-86b2-e8878755e0f0.png)

**Comment by gyeonglin** [comment]
1. 김경린
2. https://github.com/kyoungLin/NEXT_HW/tree/master/Session1_HW
3. 
![캡처](https://user-images.githubusercontent.com/35323804/112449218-802d5f00-8d96-11eb-97d7-5c23fd38e63e.PNG)
![캡처2](https://user-images.githubusercontent.com/35323804/112449688-03e74b80-8d97-11eb-948f-de8248f7a90e.PNG)

**Comment by zznbbang** [comment]
1. 양진영
2. https://github.com/zznbbang/REPOSITORY_HW/tree/master/SESSION_01
3. 
![image](https://user-images.githubusercontent.com/80868193/112449566-ddc1ab80-8d96-11eb-92b4-3bddd139f297.png)
![image](https://user-images.githubusercontent.com/80868193/112451000-537a4700-8d98-11eb-980f-f814e0d7e399.png)

**Comment by yilin-kim** [comment]
1. 김이린
2. https://github.com/yilin-kim/LikeLionSessionHW/tree/master/Session1_HW
3. 
![image_capture_004](https://user-images.githubusercontent.com/63697053/112450113-5fb1d480-8d97-11eb-976b-18dd9b55ad92.PNG)

**Comment by pcw9341** [comment]
1.박채원
2.https://github.com/pcw9341/Repository_HW/tree/master/second_HW
3.
![blog-1](https://user-images.githubusercontent.com/80807025/112452322-db148580-8d99-11eb-922a-5757d5a47b1f.PNG)

**Comment by kyliecamila** [comment]
1.강미지
2.https://github.com/kyliecamila/session1hw
3.
![블로그](https://user-images.githubusercontent.com/80819760/112452977-8b828980-8d9a-11eb-8836-fe460e723725.png)

**Comment by Minyongggg** [comment]
1. 이민용
2. https://github.com/Minyongggg/Next_hw/tree/master/Session1_HW
3. 
![blog_fullshot](https://user-images.githubusercontent.com/54466093/112453088-a9e88500-8d9a-11eb-9c1c-9a500f087ac1.jpg)

**Comment by jiyoon27** [comment]
1. 정지윤
2. https://github.com/jiyoon27/NEXT_HW/tree/master/Session_1
3. 
<img width="1440" alt="스크린샷 2021-03-25 오후 6 47 21" src="https://user-images.githubusercontent.com/80808647/112453334-efa54d80-8d9a-11eb-92dc-28ef216531ec.png">
<img width="1425" alt="hw final" src="https://user-images.githubusercontent.com/80808647/112455632-3eec7d80-8d9d-11eb-828c-cc475531c33d.png">

**Comment by 45-5DC** [comment]
1. 이상헌
2. https://github.com/45-5DC/NEXT_HW/tree/master/Session1_HW
3. 
![image](https://user-images.githubusercontent.com/80238753/112453782-617d9700-8d9b-11eb-8d28-6e2bf0aff07a.png)
![image](https://user-images.githubusercontent.com/80238753/112453805-680c0e80-8d9b-11eb-812f-a57abab286b2.png)

**Comment by deborah91298** [comment]
1. 전혜린
2. https://github.com/deborah91298/NEXTLikeLion/tree/master/Session1_HW
3.
![my_blog_screenshot](https://user-images.githubusercontent.com/75147564/112454999-a3f3a380-8d9c-11eb-88c0-aaf2d9d55395.png)
![my_blog_screenshot_scorn](https://user-images.githubusercontent.com/75147564/112454954-93432d80-8d9c-11eb-829d-b9fe3178bf02.png)
![my_blog_screenshot_scone](https://user-images.githubusercontent.com/75147564/112485984-d4e4d000-8dbe-11eb-9e73-efad132b524f.png)

**Comment by developpeurenmoi** [comment]
1. 진서동
2. https://github.com/developpeurenmoi/Homework/tree/master/Session1_HW
3. 
![블로그01](https://user-images.githubusercontent.com/80775477/112454296-e23c9300-8d9b-11eb-9d18-9eee5f5d407f.PNG)
![블로그02](https://user-images.githubusercontent.com/80775477/112454335-ebc5fb00-8d9b-11eb-89c1-fb1d0767906c.PNG)

**Comment by shinwr** [comment]
1. 신원령
2. https://github.com/shinwr/Hw.git
3. 
![블로그1](https://user-images.githubusercontent.com/80866551/112455656-4744b880-8d9d-11eb-9ee8-a3968245230c.png)
![블로그2](https://user-images.githubusercontent.com/80866551/112455669-49a71280-8d9d-11eb-9df4-61ec97420f24.png)
![블로그3](https://user-images.githubusercontent.com/80866551/112455676-4ad83f80-8d9d-11eb-92c7-1d3d017be2c1.png)
![블로그4](https://user-images.githubusercontent.com/80866551/112455679-4b70d600-8d9d-11eb-97a7-bfce13b58efb.png)

**Comment by Jamiejaja** [comment]
1. 이재아
2. https://github.com/Jamiejaja/NEXT_HW.git
3. 
![Uploading BLOG.png…]()

**Comment by dlwnsdud1104** [comment]
1. 이준영
2. https://github.com/dlwnsdud1104/HWRepository.git
3. 
<img width="1431" alt="블로그1" src="https://user-images.githubusercontent.com/80838671/112456294-f97c8000-8d9d-11eb-9707-27d64a483c16.png">
![Uploading 블로그2.png…]()
![Uploading 블로그3.png…]()
![Uploading 블로그4.png…]()

**Comment by heawon99** [comment]
1. 양희원
2. https://github.com/heawon99/Repository-NEXT_HW
3. 
![홈페이지](https://user-images.githubusercontent.com/80876231/112470660-4700e900-8dae-11eb-899e-ee8942a7761b.png)

**Comment by onCloud33** [comment]
1. 양효령
2. https://github.com/HyoRyoung-Yang/NEXT_HW2
3. 
![Ryoung's blog](https://user-images.githubusercontent.com/80874190/112536842-4b9ac100-8df1-11eb-8f15-4fdfd7e8a800.png)

**Comment by gjivaeri** [comment]
1.박설진
2.https://github.com/gjivaeri/NEXT_HW/tree/master/session1_HW
3.
![blog1](https://user-images.githubusercontent.com/66814071/112597806-f9898800-8e50-11eb-9a36-9ddd80e9dfdc.png)

늦어서 죄송합니다.

**Comment by Kim-Jiseong** [comment]
1.김지성
2.https://github.com/Kim-Jiseong/NEXT_HW.git
3.
![화면 캡처](https://user-images.githubusercontent.com/35622664/112615910-6eb38800-8e66-11eb-9a64-f87fe9a714e5.png)

**Comment by gadongkim** [comment]
1. 김가현
2. https://github.com/gadongkim/NEXT_HW
3. 
<img width="1440" alt="blog" src="https://user-images.githubusercontent.com/69626443/112678088-e0fb8b00-8ead-11eb-932c-bbedd4e7c179.png">
